on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: true
      your-company:
        type: string
        required: true
      env-name:
        type: string
        required: true
    outputs:
      dns:
        description: "dns of loadbalancer/endpoint"
        value: ${{ jobs.create-aws-opta.outputs.dns }}

jobs:
  create-aws-opta:
    name: Create AWS OPTA
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::896381257720:role/GitHubAdmin"
          aws-region: ${{ inputs.aws-region }}
          role-session-name: ApplySession
      - name: Checkout repo
        uses: actions/checkout@v3
        # move the below to CI helper?
      - name: set env variables
        shell: bash
        run: |
          sed -i "s/<env_name>/${{ inputs.env-name }}/" /home/runner/work/flyte/flyte/opta/aws/env.yaml
          sed -i "s/<your_company>/${{ inputs.your-company }}/" /home/runner/work/flyte/flyte/opta/aws/env.yaml
          sed -i "s/<region>/${{ inputs.aws-region }}/" /home/runner/work/flyte/flyte/opta/aws/env.yaml
          sed -i "s/<account_id>/${{ secrets.AWS_ACCOUNT_ID }}/" /home/runner/work/flyte/flyte/opta/aws/env.yaml
      - name: cat aws env
        shell: bash
        run: |
          cat /home/runner/work/flyte/flyte/opta/aws/env.yaml
      - name: Archive env artifact
        uses: actions/upload-artifact@v3
        with:
          name: opta-env
          path: |
            ./opta/aws/env.yaml
      - name: SETUP AND APPLY OPTA
        shell: bash
        run: |
          sudo chmod +x /home/runner/work/flyte/flyte/.github/scripts/ci_helper.sh
          /home/runner/work/flyte/flyte/.github/scripts/ci_helper.sh setup_opta
          cat /home/runner/work/flyte/flyte/opta/aws/env.yaml
          opta apply -c /home/runner/work/flyte/flyte/opta/aws/env.yaml --auto-approve
          opta output -c /home/runner/work/flyte/flyte/opta/aws/env.yaml
      - name: OPTA DNS
        id: opta-dns
        shell: bash
        run: |
          cat /home/runner/work/flyte/flyte/opta/aws/env.yaml
          DNS=$(opta output -c /home/runner/work/flyte/flyte/opta/aws/env.yaml | jq -r .load_balancer_raw_dns)
          echo ""
          echo $DNS
          echo "::set-output name=dns::${DNS}"
    outputs:
      dns: ${{ steps.output-dns.outputs.dns }}
