on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: true
      your-company:
        type: string
        required: true
      env-name:
        type: string
        required: true
    outputs:
      dns:
        type: string
        description: "dns of loadbalancer/endpoint"


jobs:
  destroy-cluster:
    name: Create Opta Env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: set env variables
        # MAYBE MOVE THIS TO CI_HELPER?
        shell: bash
        run: |
          sed -i "s/<env_name>/${{ inputs.env-name }}/" ./opta/aws/env.yaml
          sed -i "s/<your_company>/${{ inputs.your-company }}/" ./opta/aws/env.yaml
          sed -i "s/<region>/${{ inputs.aws-region }}/" ./opta/aws/env.yaml
          sed -i "s/<account_id>/${{ secrets.AWS_ACCOUNT_ID }}/" ./opta/aws/env.yaml
      - name: Archive env artifact
        uses: actions/upload-artifact@v3
        with:
          name: opta-env
          path: |
            ./opta/aws/env.yaml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # This aws account should have admin permissions
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: "arn:aws:iam::896381257720:role/GitHubAdmin"
          aws-region:  ${{ inputs.aws-region }}
          role-session-name: ApplySession
      - name: SETUP AND APPLY OPTA
        shell: bash
        run: |
          sudo chmod +x .github/scripts/ci_helper.sh
          .github/scripts/ci_helper.sh setup_opta
          opta apply -c ./opta/aws/env.yaml --auto-approve
          opta output -c ./opta/aws/env.yaml
      - name: OPTA DNS
        id: opta-dns
        shell: bash
        run: |
          cat ./opta/aws/env.yaml
          DNS=$(opta output -c ./opta/aws/env.yaml | jq -r .load_balancer_raw_dns)
          echo ""
          echo $DNS
          echo "::set-output name=dns::${DNS}"