on:
  workflow_call:
    inputs:
      mode:
        type: string
        required: true
      components_version:
        type: string
        required: true
      aws-region:
        type: string
        required: true

jobs:
  create-opta-flyte:
    name: Create OPTA FLYTE
    runs-on: ubuntu-latest
    steps:

