on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: false
    secrets:
      AWS_IAM_ROLE_ARN_FOR_GITHUB:
        required: true

jobs:
  destroy-cluster:
    name: Destroy Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        id: download-flyte-yaml
        with:
          name: opta-flyte
          path: /home/runner/work/flyte/flyte/opta/cloud
      - uses: actions/download-artifact@v3
        id: download-env-yaml
        with:
          name: opta-env
          path: /home/runner/work/flyte/flyte/opta/cloud
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN_FOR_GITHUB }}
          role-session-name: DestroySession
          aws-region: ${{ inputs.aws-region }}
      - name: SETUP AND DESTROY OPTA
        shell: bash
        run: |
          sudo chmod +x /home/runner/work/flyte/flyte/.github/scripts/ci_helper.sh
          /home/runner/work/flyte/flyte/.github/scripts/ci_helper.sh setup_opta
      - name: DESTROY FLYTE Opta
        shell: bash
        run: |
          cd /home/runner/work/flyte/flyte/opta/cloud/
          opta destroy -c flyte.yaml --auto-approve
      - name: DESTROY OPTA ENV
        shell: bash
        run: |
          cd /home/runner/work/flyte/flyte/opta/cloud/
          opta destroy -c env.yaml --auto-approve
