on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: false

jobs:
  destroy-cluster:
    name: Destroy Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        id: download-flyte-yaml
        with:
          name: opta-flyte
          path: /home/runner/work/flyte/flyte/opta/cloud
      - uses: actions/download-artifact@v3
        id: download-env-yaml
        with:
          name: opta-env
          path: /home/runner/work/flyte/flyte/opta/cloud
      - name: TREE
        shell: bash
        run: |
          sudo apt-get -y install tree
          tree
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # This aws account should have admin permissions ...?
          role-to-assume: "arn:aws:iam::896381257720:role/GitHubAdmin"
          aws-region: ${{ inputs.aws-region }}
          role-session-name: DestroySession
      - name: SETUP OPTA
        shell: bash
        run: |
          sudo chmod +x /home/runner/work/flyte/flyte/.github/scripts/ci_helper.sh
          /home/runner/work/flyte/flyte/.github/scripts/ci_helper.sh setup_opta
      - name: DESTROY FLYTE Opta
        shell: bash
        run: |
          echo `pwd`
          cd /home/runner/work/flyte/flyte/opta/cloud/
          echo `pwd`
          echo `ls`
          sudo apt-get -y install tree
          tree
          opta destroy -c flyte.yaml --auto-approve
      - name: DESTROY OPTA ENV
        shell: bash
        run: |
          cd /home/runner/work/flyte/flyte/opta/cloud/
          opta destroy -c env.yaml --auto-approve
