on:
  workflow_call:
    inputs:
      flyte-storage-bucket:
        type: string
        required: true
      aws-region:
        type: string
        required: true
      dns:
        type: string
        required: true
    secrets:
      AWS_ACCOUNT_ID:
        required: true

jobs:
  do-job:
    runs-on: ubuntu-latest
    steps:
    - name: set flyte variables
      shell: bash
      run: |
        sed -i "s/<unique_bucket_name>/${{ inputs.flyte-storage-bucket }}/" /home/runner/work/flyte/flyte/opta/aws/flyte.yaml
        sed -i "s/<region>/${{ inputs.aws-region }}/" /home/runner/work/flyte/flyte/opta/aws/flyte.yaml
        sed -i "s/<account_id>/${{ env.AWS_ACCOUNT_ID }}/" /home/runner/work/flyte/flyte/opta/aws/flyte.yaml
        sed -i "s/<cluster_ingress>/${{ steps.opta-dns.outputs.dns }}/" /home/runner/work/flyte/flyte/opta/aws/flyte.yaml
    # REMOVE THIS STEP!? IS HERE FOR DEBUG...
    - name: view flyte.yaml
      shell: bash
      run: |
        cat /home/runner/work/flyte/flyte/opta/aws/flyte.yaml
    - name: Archive env artifact
      uses: actions/upload-artifact@v3
      with:
        name: opta-flyte
        path: |
          /home/runner/work/flyte/flyte/opta/aws/flyte.yaml