on:
  push:
    branches:
      - opta-aws

jobs:
  testing-workflows:
    runs-on: ubuntu-latest
      steps:
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1  
        with: 
          # This aws account should have admin permissions
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}  
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-east-1 

      - name: Create bucket
        shell: bash
        run: |
          aws s3 mb totally-unique-bucket-name-12354
