on:
  push:
    branches:
      - opta-aws

env:
  ENV_NAME: development
  YOUR_COMPANY: bamboozoology
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "${{ secrets.AWS_ACCOUNT_ID }}"
  WORKING_LOCATION: brucearctor/flyte/.github/workflows/setup_nightly_and_release.yml@opta-aws

jobs:
  setup-nightly-and-release-workflows:
    uses: "${{ WORKING_LOCATION }}"
  cat-stuff:
    uses: ubuntu-latest
    - name: cat file
      shell: bash
      run: |
        cat ./opta/aws/env.yaml



