on:
  push:
    branches:
      - opta-aws

env:
  ENV_NAME: development
  YOUR_COMPANY: bamboozoology
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "${{ secrets.AWS_ACCOUNT_ID }}"

jobs:
  testing-workflows:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1  
      with: 
        # This aws account should have admin permissions
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}  
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: us-east-1 
    - name: Download Opta
      shell: bash
      run: |
        /bin/bash -c "$(curl -fsSL https://docs.opta.dev/install.sh)"
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: set variables
      shell: bash
      run: |
        sed -i 's/<env_name>/$ENV_NAME/g' ./opta/aws/env.yaml; sed -i 's/<your_company>/$YOUR_COMPANY/g' ./opta/aws/env.yaml; sed -i 's/<region>/$REGION/g' ./opta/aws/env.yaml; sed -i 's/<account_id>/$AWS_ACCOUNT_ID/g' ./opta/aws/env.yaml; 
    - name: APPLY Opta
      shell: bash
      run: |
        /home/runner/.opta/opta apply -c ./opta/aws/env.yaml --auto-approve 
    - name: DESTROY Opta
      shell: bash
      run: |
        /home/runner/.opta/opta destroy -c ./opta/aws/env.yaml --auto-approve 



