on:
  push:
    branches:
      - opta-aws

env:
  ENV_NAME: development
  COMPANY: bamboozoology
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  testing-workflows:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1  
      with: 
        # This aws account should have admin permissions
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}  
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: us-east-1 
    - name: Download Opta
      shell: bash
      run: |
        yes | curl -fsSL https://docs.opta.dev/install.sh
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: APPLY Opta
      shell: bash
      run: |
        ~/.opta/opta apply -c ./opta/aws/env.yaml --var env_name=$ENV_NAME --var company=$COMPANY --var aws_region=$AWS_REGION  --var=aws_account_id=$AWS_ACCOUNT_ID --auto-approve 
    - name: DESTROY Opta
      shell: bash
      run: |
        ~/.opta/opta destroy -c ./opta/aws/env.yaml --var env_name=$ENV_NAME --var company=$COMPANY --var aws_region=$AWS_REGION  --var=aws_account_id=$AWS_ACCOUNT_ID --auto-approve 



